version: '3'

services:
  db:
    container_name: mean-db
    image: mongo:5.0.16
    volumes:
      - C:/Users/jomap/Desktop/nest-backend/mongo:/data/db
    ports:
      - 27017:27017
    restart: always
